# Generated by Django 4.1.7 on 2023-03-05 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=25, unique=True, verbose_name='CPF/CNPJ')),
                ('state_registration', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='I.E')),
                ('corporate_name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('fantasy_name', models.CharField(max_length=255, verbose_name='Nome Fanstasia')),
                ('logo', models.CharField(max_length=10, null=True, verbose_name='Logo')),
                ('banner', models.CharField(max_length=10, null=True, verbose_name='Banner')),
                ('primary_color', models.CharField(blank=True, default='#FF5733', max_length=15, null=True, verbose_name='Cor Primaria')),
                ('secondary_color', models.CharField(blank=True, default='#32D31C', max_length=15, null=True, verbose_name='Cor Secundaria')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('public_observation', models.TextField(blank=True, null=True, verbose_name='Observação Publica')),
                ('private_observation', models.TextField(blank=True, null=True, verbose_name='Observação Privada')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='CompanyEstablishmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Empresa - Tipo de Estabelecimento',
                'verbose_name_plural': 'Empresa - Tipos de Estabelecimento',
            },
        ),
        migrations.CreateModel(
            name='CompanyPhoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Empresa - Tipo de Telefone',
                'verbose_name_plural': 'Empresa - Tipos de Telefone',
            },
        ),
        migrations.CreateModel(
            name='CompanySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Empresa - Porte',
                'verbose_name_plural': 'Empresa - Portes',
            },
        ),
        migrations.CreateModel(
            name='CompanyPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa')),
                ('phone_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.companyphonetype', verbose_name='Tipo de Telefone')),
            ],
            options={
                'verbose_name': 'Empresa - Telefone',
                'verbose_name_plural': 'Empresa - Telefones',
            },
        ),
        migrations.CreateModel(
            name='CompanyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Empresa - Email',
                'verbose_name_plural': 'Empresa - Emails',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.companysize', verbose_name='Porte'),
        ),
        migrations.AddField(
            model_name='company',
            name='establishment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.companyestablishmenttype', verbose_name='Tipo Estabelecimento'),
        ),
    ]
