# Generated by Django 4.1.7 on 2023-03-06 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Empresa - Tipo de Pagamento',
                'verbose_name_plural': 'Empresa - Tipos de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='CompanyRegistrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Empresa - Situação Cadastro',
                'verbose_name_plural': 'Empresa - Situações Cadastro',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='payment_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='company.companypaymentstatus', verbose_name='Status Pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='registration_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='company.companyregistrationstatus', verbose_name='Situação Cadastro'),
            preserve_default=False,
        ),
    ]
